"""Aggregate per-opponent gauntlet eval JSONs into a single markdown report."""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def wilson_interval(wins: int, n: int, z: float = 1.96) -> tuple[float, float]:
    """Two-sided Wilson score interval for a binomial proportion."""
    if n <= 0:
        return (0.0, 0.0)
    phat = wins / n
    denom = 1.0 + z * z / n
    centre = (phat + z * z / (2.0 * n)) / denom
    half = (z * math.sqrt(phat * (1.0 - phat) / n + z * z / (4.0 * n * n))) / denom
    return (max(0.0, centre - half), min(1.0, centre + half))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output_dir")
    parser.add_argument("--checkpoint", default="(unknown)")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    json_files = sorted(p for p in out_dir.glob("*.json") if not p.name.endswith("_shards.json"))
    if not json_files:
        raise SystemExit(f"No JSON files found in {out_dir}")

    rows: list[dict] = []
    for path in json_files:
        # Skip nested shard summaries
        if path.parent != out_dir:
            continue
        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError:
            continue
        if "matches" not in data or "learned" not in data:
            continue
        matches = int(data.get("matches", 0))
        wins = int((data.get("learned") or {}).get("wins", 0))
        lo, hi = wilson_interval(wins, matches)
        rows.append({
            "opponent": data.get("opponentProfile", path.stem),
            "matches": matches,
            "wins": wins,
            "win_rate": wins / matches if matches else 0.0,
            "ci_lo": lo,
            "ci_hi": hi,
            "net_level_per_match": float(data.get("netLevelDeltaPerMatch", 0.0)),
            "duplicate_deals": data.get("duplicateDeals", None),
        })

    rows.sort(key=lambda r: r["opponent"])
    lines: list[str] = []
    lines.append(f"# ScoreNet gauntlet report")
    lines.append("")
    lines.append(f"- Checkpoint: `{args.checkpoint}`")
    lines.append(f"- Report dir: `{out_dir}`")
    if rows:
        any_dup = any(r["duplicate_deals"] for r in rows)
        lines.append(f"- Duplicate dealing: `{'yes' if any_dup else 'no'}`")
    lines.append("")
    lines.append("| Opponent | Matches | Win rate | 95% Wilson CI | Net level / match |")
    lines.append("|---|---:|---:|---|---:|")
    for r in rows:
        lines.append(
            f"| {r['opponent']} | {r['matches']} | "
            f"{r['win_rate']*100:.1f}% | "
            f"[{r['ci_lo']*100:.1f}%, {r['ci_hi']*100:.1f}%] | "
            f"{r['net_level_per_match']:+.3f} |"
        )
    lines.append("")
    lines.append("Generated by `training/scorenet/aggregate_gauntlet.py`.")

    Path(args.output).write_text("\n".join(lines) + "\n")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
